### ISSUE TITLE
Add a loading animation until it fetches data from the api

### ISSUE THREAD

**Issue by lazyjinchuriki** [lazyjinchuriki/pokedex#1]

**Comment by Light13008** [comment]
please assign this to me,  I can work on this

**Comment by lazyjinchuriki** [comment]
> please assign this to me,  I can work on this
> 
> 

Fork the repo, clone it in you personal machine, make the necessary changes and create a pull request.
I'll definitely merge it. 😄
BEST OF LUCK!
