### ISSUE TITLE
Incorrect Topic

### ISSUE THREAD

**Issue by naomi-lgbt** [lazyjinchuriki/pokedex#12]
Heya!

It looks like you're trying to participate in Hacktoberfest, but your topic has a typo and won't be opted in.

Update the `hactoberfest` topic to `hacktoberfest` if you want PRs to this repository to count. :3

**Comment by lazyjinchuriki** [comment]
> Heya!
> 
> It looks like you're trying to participate in Hacktoberfest, but your topic has a typo and won't be opted in.
> 
> Update the `hactoberfest` topic to `hacktoberfest` if you want PRs to this repository to count. :3

Hi there! Thanks for pointing that out,
I have fixed it. Please confirm.

**Comment by naomi-lgbt** [comment]
Perfect! You should be all set then!
