### ISSUE TITLE
Redesigning the search bar

### ISSUE THREAD

**Issue by Gaurav-576** [lazyjinchuriki/pokedex#16]
Redesigning the search bar for better searching experience

**Comment by Gaurav-576** [comment]
I would like to work on this repo for the Hacktober Fest 2023 and make some open source contributions for your project

**Comment by lazyjinchuriki** [comment]
Fork the repo and make a pull request.
I'll merge it.
Make sure it is mobile responsive.

**Comment by Khushi-Gupta13** [comment]
I would like to give it a try as a contribution to hactober fest 2023

**Comment by lazyjinchuriki** [comment]
Create a pull request. 
Make sure it is mobile responsive.

**Comment by aparna03dubey** [comment]
Please assign me this for hacktoberfest and kindly add the hacktoberfest tag.
