### ISSUE TITLE
Add new feature called weak against and strong against below stats in details.html

### ISSUE THREAD

**Issue by lazyjinchuriki** [lazyjinchuriki/pokedex#22]
remember to add the icon of types which that particular pokemon is weak or strong against.
all the data can be found in the fetch call. The UI should be the same as how it is done to show the typesof pokemon.

**Comment by lokesh-wagh** [comment]
hey!!
I can work on this 

can you assign me this issue

**Comment by lokesh-wagh** [comment]
Also the api just provide's a way to know how the damage change's

like double damage , half damage , no damage

what would be the criteria for a type being strong against a type and weak against a type

**Comment by lazyjinchuriki** [comment]
Double damage to means strong against and no damage means weak against maybe.
There are other factors i think like iv, ev, level etc but we can Ignore that.
If you manage to know some other information you can implement it I have no problem with that.
Best of Luck

**Comment by lokesh-wagh** [comment]
should i display only the icon's or the name of the type beside icon

**Comment by lazyjinchuriki** [comment]
Only the icons exactly like shown in the Types in the overview.
You can add a heading saying "Weakness"
And "Strong Against".
