### ISSUE TITLE
No favicon icon on the website

### ISSUE THREAD

**Issue by SumitVerma-coder** [lazyjinchuriki/pokedex#23]
Currently no favicon icon is present on the website.
![image](https://github.com/lazyjinchuriki/pokedex/assets/112965155/12ad9273-dd2e-4a6d-9874-d1b2eb0fb8ab)
**_PLEASE ASSIGN ME THIS ISSUE UNDER HACTOBERFEST TAG_**

**Comment by lazyjinchuriki** [comment]
It will be great to add a pokeball icon.

**Comment by SumitVerma-coder** [comment]
Got it.
