### ISSUE TITLE
Fix: flicker when hovering on cards

### ISSUE THREAD

**Issue by Shubhamm33** [lazyjinchuriki/pokedex#26]
issue: There is a flickering issue when hovering on the card
https://github.com/lazyjinchuriki/pokedex/assets/38568811/3805857a-e952-4962-9c9e-791f58b656bf

**Comment by lazyjinchuriki** [comment]
I can assign this issue to you under Hactoberfest.
Can you work on that?

**Comment by Shubhamm33** [comment]
Yes i've forked it, theres also some js issue in console..
i'll fix that too

**Comment by AniketP04** [comment]
I'm willing to work on this issue and collaborate with the maintainers. Please let me know how I can proceed.

**Comment by Kelvin-K** [comment]
I saw the issue was still pending so I went ahead and created a pull request.
If you find this suitable, please assign this issue to me.

**Comment by Shubhamm33** [comment]
Okay awesome...
i have pulled the updated
there are minor errors displaying in console..
fixed them as well...
please merge the updated, sending a PR
![t19](https://github.com/lazyjinchuriki/pokedex/assets/38568811/0591af90-e4ef-490e-aab9-983c148ac4fd)

**Comment by lazyjinchuriki** [comment]
Thanks.

**Comment by Shubhamm33** [comment]
There are 2 errors which i'm getting,
one for the images, which i'm ignoring since its loading on your end...

Other one is the /v2/type error... 
for some pokemon /v2/type is not present in their response structure...
there are only 20 pokemon links available on the types endpoint

![t20](https://github.com/lazyjinchuriki/pokedex/assets/38568811/c4143097-f41d-4bef-9092-828893ea1814)
![t21](https://github.com/lazyjinchuriki/pokedex/assets/38568811/39505fee-1508-4205-ac75-9ccb6e923944)
After 18 it has nothing, which gives error

i have also checked their documentation, it returns undefined for pokemon after 18,  since its not present in the response body itself
![t22](https://github.com/lazyjinchuriki/pokedex/assets/38568811/e5b1b400-24b3-4c7e-8777-9185e5eecfe0)
![t23](https://github.com/lazyjinchuriki/pokedex/assets/38568811/12722164-d580-46d2-9e46-32f69077a8bf)

Do you know why is that ?
I'm not able to understand, they dont have any issue in their docs as well..

**Comment by lazyjinchuriki** [comment]
You see the type endpoint does not refer to each pokemon, instead it refers to each types (i.e. fire, water etc.)
There are only 20-21 types i think thus it will return undefined for more than that.
This issue is because someone created a PR for showing Strong Against and Weak Against types and I unknowingly merged it.

**Comment by Shubhamm33** [comment]
ohh okay got it now...
so first we need to fetch the pokemon type from pokemon, then their respective type data using this type endpoint...
i'll try this out then let you know

**Comment by lazyjinchuriki** [comment]
You're the best!!

**Comment by Shubhamm33** [comment]
Thankyou so much
i'll probably work on this in evening, currently in office!
