### ISSUE TITLE
Fix: pokemon image not showing

### ISSUE THREAD

**Issue by Shubhamm33** [lazyjinchuriki/pokedex#27]
issue: Image of pokemon is not loaded on the card
![t18](https://github.com/lazyjinchuriki/pokedex/assets/38568811/1c869558-bb13-48e5-89fc-f4cb2a499b79)

**Comment by Shubhamm33** [comment]
Please assign this issue #27 or #26 to me i'm working on it

**Comment by lazyjinchuriki** [comment]
Internet Issue.
