### ISSUE TITLE
Alignment is getting distorted while searching.

### ISSUE THREAD

**Issue by lunoos** [lazyjinchuriki/pokedex#32]
Hi, 
I was going through the project and noticed that when something is typed in the search bar the results that appiers are distorted.
I want to fix this issue can you please assign it to me so that I can start working on it, also please tag this issue with hacktoberfest tag.

Below is the ss of the issue that I pointed out.

![image](https://github.com/lazyjinchuriki/pokedex/assets/65530077/ef416ee4-1633-4536-81d6-91f58b9e3d25)

**Comment by lazyjinchuriki** [comment]
yea I've noticed that. I'm assigning this issue to you under hacktoberfest.

**Comment by lunoos** [comment]
Following is the SS after code changes:
![image](https://github.com/lazyjinchuriki/pokedex/assets/65530077/3a434356-61de-4990-b7ca-b488b029421b)
