### ISSUE TITLE
spinning effect on pokeball

### ISSUE THREAD

**Issue by Seemant-RajSingh** [lazyjinchuriki/pokedex#45]
can add spinning animation to pokeball on top left, please assign under hacktoberfest.

**Comment by lazyjinchuriki** [comment]
Sure

**Comment by Seemant-RajSingh** [comment]
PR made, check it out https://github.com/lazyjinchuriki/pokedex/pull/50

features added:

1. pokeball spin animation on hover.
2. github icon transition on hover smoothened.
3. minor bug fix - on github hover, headers elements shifted left, bug fixed.
