### ISSUE TITLE
Text from back side of card visible on mobile

### ISSUE THREAD

**Issue by michaelhhogue** [lazyjinchuriki/pokedex#56]
For reference I am on iPhone 13 Pro.

![IMG_1711](https://github.com/lazyjinchuriki/pokedex/assets/18507739/1cab03f1-d193-419e-9684-9613f9e82e02)

**Comment by lazyjinchuriki** [comment]
Cany you please look into that.

**Comment by michaelhhogue** [comment]
Will do
