### ISSUE TITLE
Adding Dark/light toggle 

### ISSUE THREAD

**Issue by nerdyawedee** [lazyjinchuriki/pokedex#8]
in the pokedex .html
assign me @lazyjinchuriki

**Comment by nerdyawedee** [comment]
please label it @lazyjinchuriki

**Comment by BarunAaryan** [comment]
I can help you with this please assign me the issue.

**Comment by nerdyawedee** [comment]
@lazyjinchuriki  I think i have made necessary change that you asked me to do in my PR you can review the changes

**Comment by lazyjinchuriki** [comment]
Merged the pull request.
